### ISSUE TITLE
My Account- Edit Profile- There is OTP Is sent to your mobile no., so I can't update my mobile no.

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#1]
**Steps:**

1. Login through Gmail
2. Click on My Account
3. Click on Edit Profile
4. Click on Update Mobile Number 
5. Choose **EG +20**, enter your mobile no.
6. Click on **Request OTP**.

**Actual Result:** 
There is OTP Is sent to your mobile no., so I can't update my mobile no.

**Expected Result:**
An otp should be sent to my mobile no.

**Comment by enuat** [comment]
Already answered @ closed @ https://github.com/MirnaHamdy/Yajny/issues/29

Please verify and mark it as closed.

**Comment by Msebaie2** [comment]
Closed
