### ISSUE TITLE
After clicking on Join Now will navigate to the sign-up page but fields don't appear.

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#10]
**Steps:**
1. Navigate to the homepage 
2. Click on Drop-down menu
3. Click on Join Now

**Actual Result:**
After clicking on Join Now will navigate to the sign-up page but fields don't appear.
You should refresh the URL to let fields appear.

**Expected Result:**
Once you click on Join Now  all sign-up fields should appear

**Comment by enuat** [comment]
Fixed.

**Comment by Msebaie2** [comment]
Tested and working
closed
