### ISSUE TITLE
See All Stores- Buttons texts are cut not the whole text appears.

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#11]
**Steps:**

1. Navigate to the homepage.
2. Click on the drop-down menu.
3. Click on See All Stores.
4. Check 2 buttons below all stores title

**Actual Result**
Buttons texts are cut not the whole text appears.
https://drive.google.com/file/d/1KfnmwdiMpMbcuNCE4PtTjylbtdhImzgT/view?usp=sharing

**Expected Result:**
Buttons whole should appear on Mobile.

**Comment by Msebaie2** [comment]
any updates

**Comment by Msebaie2** [comment]
solved
