### ISSUE TITLE
Free Shipping- The banner image appears as a  cut image on Mobile.

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#12]
1. Navigate to the homepage
2. Click on Latest Offers drop-down menu
3. Click on Free Shipping
 
**Actual Result:**
The banner image appears as a  cut image on Mobile.
https://drive.google.com/file/d/1mI_BPxJ0D4lmWCDCSb9-TDyGfPtPEtSh/view?usp=sharing

**Expected Result:**
The whole image should responsive.

**Comment by Msebaie2** [comment]
any updates

**Comment by Msebaie2** [comment]
free shipping tab not available on staging.

**Comment by enuat** [comment]
Free shipping was as one of the tags..

The behaviour is same as any other tag.

You can verify this by visiting 

https://staging.yajny.enactweb.com/en/coupon-tag/flight

For us, it looks fine.

![image](https://user-images.githubusercontent.com/58430125/71338184-e82e3d80-2574-11ea-8166-0cd2bed521d7.png)

**Comment by Msebaie2** [comment]
closed
