### ISSUE TITLE
I Navigated to the free shipping page through the latest offers drop-down menu so the item prop All Tags shouldn't appear.

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#13]
1. Navigate to the Homepage
2. Click on the Latest Offers hamburger menu
3. Click on Free Shipping item

**Actual Result:**
Item scope  **Home >All Tags > Free Shipping** is wrong
I Navigated to the free shipping page through the latest offers drop-down menu so the item props **All Tags** shouldn't appear.

https://drive.google.com/file/d/1vm2nJjKzNj9RjdGr2enfIZBtPLlaauOU/view?usp=sharing

**Expected Result:** 
The correct one which should appear instead of all tags is **Latest Offers**

So the correct Item scope is
**Home >Latest Offers >Free Shipping**

**Comment by enuat** [comment]
"A breadcrumb trail on a page indicates the page's position in the site hierarchy. A user can navigate all the way up in the site hierarchy, one level at a time, by starting from the last breadcrumb in the breadcrumb trail."

It's not used to show the user flow. "Latest Offers" is just a Menu you have created to link it and tomorrow it might be removed, but Home->All Tags-> Free Shipping is always accessible.

 
Further Reading

https://developers.google.com/search/docs/data-types/breadcrumb

**Comment by enuat** [comment]
Please consult with SEO Person and verify this, let us know if any change is needed

**Comment by Msebaie2** [comment]
Free shipping tab not available on staging

**Comment by enuat** [comment]
It was one of the tags in menu.. in staging website, we've removed dummy content.

You may configure and add it in menu.

And for breadcrumb structure change, we've implemented as per industry best practice, yet if you wish any change, please let's know.

**Comment by Msebaie2** [comment]
closed
