### ISSUE TITLE
Sign up using fake referral code

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#16]
If I insert wrong referral code, and press Enter, Join tab changed to please wait without any confirmation, and have to refresh the page to be able to retry, while I should face (The selected referrer code is invalid.) error.
![image](https://user-images.githubusercontent.com/58039276/69347092-93995900-0c7c-11ea-9bde-1f825c15906a.png)
Time Stamp: 11/21/2019   11:46 AM

**Comment by enuat** [comment]
Can you check, its working fine

https://prnt.sc/q9dcuw

and

https://prnt.sc/q9dd2x

I tested with multiple emails, including "mostafa.elsebaie@outlook.com"

**Comment by Msebaie2** [comment]
Solved and Closed
