### ISSUE TITLE
Use Referral code

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#17]
The highlighted question in yellow color should be ended with a question mark.
![image](https://user-images.githubusercontent.com/58039276/69347301-e1ae5c80-0c7c-11ea-80f8-7aac2b4f5bf7.png)
Time Stamp 11/21/2019  11:54:00 AM

**Comment by enuat** [comment]
The last character is question mark only..

Let's know if you wish to change it something else.

**Comment by Msebaie2** [comment]
![image](https://user-images.githubusercontent.com/58039276/70521184-72bf7780-1b47-11ea-94e9-2ce80361c520.png)

Need to be ended like that pic (https://www.rakuten.com/)

**Comment by enuat** [comment]
I think the font given by your team itself as such UI. 

https://prnt.sc/q9def3

https://prnt.sc/q9df2b

https://fonts.adobe.com/fonts/century-gothic

**Comment by Msebaie2** [comment]
Could you please update the font with attached file.
and please advice how we can change the Logo from the header.
and we need to change the background of header to be white.

[Konnect Font-20191003T095729Z-001.zip](https://github.com/MirnaHamdy/Yajny/files/3951128/Konnect.Font-20191003T095729Z-001.zip)

**Comment by Msebaie2** [comment]
We need to use the below Logo instead of current one

![Logo PNG](https://user-images.githubusercontent.com/58039276/70635602-e2635e80-1c3c-11ea-8861-1f980710f169.png)

**Comment by enuat** [comment]
Please create a relevant discussion for this on CRM, as this is not an issue, we can close it.  

Also, it will be great if we can get psd/ai file, so we can resize it as per the website and app requirement.
