### ISSUE TITLE
Terms & condition confirmation

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#18]
There   is no Check box to confirm terms & conditions

![image](https://user-images.githubusercontent.com/58039276/69347374-0571a280-0c7d-11ea-85eb-d4947c05371e.png)

Time Stamp: 11/21/2019  11:58:00 AM

**Comment by enuat** [comment]
As this is how it's with https://www.rakuten.com/ a benchmark website  @ https://prnt.sc/q8q7bk

And most cashback website wants to keep the signup as simple as possible.

**Comment by Msebaie2** [comment]
Okay, issue closed.
