### ISSUE TITLE
Sign up using FB

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#19]
After select Continue with FB, then cancel and didn't confirm the activation refer me back to error page. Go home and Contact us buttons not working.
![image](https://user-images.githubusercontent.com/58039276/69347451-2508cb00-0c7d-11ea-9e61-221e3eb06f1b.png)
Time Stamp: 11/21/2019  12:26:00 PM

**Comment by enuat** [comment]
Now it just redirects to homepage

**Comment by Msebaie2** [comment]
Solved, Thanks
