### ISSUE TITLE
My Account- Update Mobile Number- Typos

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#2]
**Steps**

1. Login through Gmail
2. Click on **My Account**
3. Click on **Edit Profile**
4. Click on **Update** Mobile Number 
5. Add invalid data in **Mobile No** field.
6. Click on **Request OTP** 

**Actual Result**
Remove comma from the validation message cause there is already full stop is added.

https://drive.google.com/file/d/1TrZcJNHMo51DZ5oTADyP1FUy90BHNViR/view?usp=sharing
**--------------------------------------------------------------------------------------------------------**
4. Click on **Update Mobile Number**
5. Add valid data in **Mobile No** field.
6. Choose **EG +20** and add valid mobile no.
7. Click on **Request OTP**.

**Actual Result**

**https://drive.google.com/file/d/1TFzf98N3NjnefzeXouLcFEC8VEHP3ARZ/view?usp=sharing**

**https://drive.google.com/file/d/1CRmlm5Kipy_2vQ8xqRXOo3j2tMl5ub7v/view?usp=sharing**

**Comment by Msebaie2** [comment]
any updates

**Comment by Msebaie2** [comment]
OTP msg sent but without OTP number, so please advice.

![IMG_0003](https://user-images.githubusercontent.com/58039276/71322193-91215d80-24cd-11ea-926f-5a0522e4e792.PNG)

**Comment by enuat** [comment]
Added;

![image](https://user-images.githubusercontent.com/58430125/71338247-1e6bbd00-2575-11ea-8be0-9c0520234a9c.png)

**Comment by Msebaie2** [comment]
![image](https://user-images.githubusercontent.com/58039276/71349923-ca62d780-2578-11ea-9fe8-f6b4fb2bb703.png)

please check mentioned SC, as we need to change USERNAME to reflect CST username on yajny

**Comment by Msebaie2** [comment]
Solved. and case closed

**Comment by Msebaie2** [comment]
https://user-images.githubusercontent.com/58039276/71349923-ca62d780-2578-11ea-9fe8-f6b4fb2bb703.png

Still need CST name to be updated.

**Comment by Msebaie2** [comment]
any updates

**Comment by enuat** [comment]
Already fixed

![image](https://user-images.githubusercontent.com/58430125/71406647-d923ba00-265e-11ea-834f-d7343625548e.png)

From staging website

**Comment by Msebaie2** [comment]
issue not solved, you just removed the tittle from it, and replace it with Verify mobile number, and i don't have issue with it. and please check the below video as the time in seconds has issue when number changed.

[media.io_screen-capture (01).zip](https://github.com/MirnaHamdy/Yajny/files/3997890/media.io_screen-capture.01.zip)

**Comment by Msebaie2** [comment]
and the SMS not sent now after your updates. please check

**Comment by enuat** [comment]
https://www.loom.com/share/b77cb005477c4830a3b060099a1f09ca

We're not able to reproduce on staging version, please check above.

Could you please remove all temp files and clear cache and try again.

**Comment by enuat** [comment]
Please try now for OTP, it should work.

**Comment by Msebaie2** [comment]
working, thanks
