### ISSUE TITLE
Sign up confirmation

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#20]
no mail received after sign up
Created E-mail : moustafa.elsebaie@gmail.com
Time Stamp: 11/21/2019  12:36:00 PM

**Comment by enuat** [comment]
Email was received in Mailtrap @ https://prnt.sc/q8qerf

Signup confirmation is not required when signed up using Google / Facebook as the very purpose of confirmation is satisfied by Google & Facebook auth. It will be redundant to have confirmation.

**Comment by Msebaie2** [comment]
Issue Closed.
