### ISSUE TITLE
Refere a friend via mail

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#21]
Can't send mail as Send mail button not working
Time Stamp: 11/21/2019  12:38:00 PM
![image](https://user-images.githubusercontent.com/58039276/69347626-7e70fa00-0c7d-11ea-9898-99ad8ae42458.png)

**Comment by enuat** [comment]
It sends the email please check mailtrap inbox and  not your actual gmail inbox.
http://prntscr.com/q5l2uc

You can ask Hany for mailtrap details, it was shared during UAT release

Just the message isn't show on submit. We have noted and will fix it.

**Comment by Msebaie2** [comment]
I found mails on mailtrap, but the button should be clickable, and there is no redirect link in the mail to register so we need to amend it.

**Comment by enuat** [comment]
Hi,

There's already a button in the email which is clickable @ https://prnt.sc/q611my

When clicked, it shows Referral code pre-applied @ https://prnt.sc/q6125d

**Comment by Msebaie2** [comment]
Retesting, and working normally, but we need to make Send email to be clickable.

![image](https://user-images.githubusercontent.com/58039276/70137431-8d50a700-1696-11ea-92c4-ac0f89143bc4.png)

**Comment by enuat** [comment]
Got it, the cursor to be a pointer and show an acknowledgment that email sent. We'll work on it during all the changes being done.

**Comment by Msebaie2** [comment]
Thanks

**Comment by Msebaie2** [comment]
Dears please check this video as "Send mail" button didn't confirm that the action has been taken so we nee to make it clickable and with popup confirmation 

[media.io_screen-capture.zip](https://github.com/MirnaHamdy/Yajny/files/3964740/media.io_screen-capture.zip)

**Comment by Msebaie2** [comment]
any updates

**Comment by enuat** [comment]
"devFixed" => Fixed on Dev/Local Version - Pending Push

We will inform you when its pushed , we have few other pending changes to be pushed together

**Comment by Msebaie2** [comment]
mails sent successfully on staging website, but not received on mailtrap mailbox

![image](https://user-images.githubusercontent.com/58039276/71321718-6384e600-24c6-11ea-9ace-e2647f69238e.png)

![image](https://user-images.githubusercontent.com/58039276/71321721-6da6e480-24c6-11ea-9ed8-6d4852b330fd.png)

**Comment by enuat** [comment]
It won't send email to registered user email ID as they've already signed up on your platform.

Please enter any new user email ID / random email ID who is not signed up yet and it will be received in mailtrap.

We've tested again now and it seems to be working fine.

![image](https://user-images.githubusercontent.com/58430125/71337510-0fcfd680-2572-11ea-84d5-2f2dc24dcb5a.png)

![image](https://user-images.githubusercontent.com/58430125/71337523-1a8a6b80-2572-11ea-897d-426c4ba96a77.png)

**Comment by Msebaie2** [comment]
Tested and closed
