### ISSUE TITLE
Registeration for referred friend

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#22]
Can't confirm registeration with Outlook mail, because Capatcha not found.
Time Stamp: 11/21/2019  12:52:00 PM
![image](https://user-images.githubusercontent.com/58039276/69347657-90eb3380-0c7d-11ea-94ab-899e26ddc656.png)

**Comment by Msebaie2** [comment]
any updates

**Comment by enuat** [comment]
We are looking into reCaptcha issue,  will revert

**Comment by enuat** [comment]
This issue occurs if google score is below 0.5, which means its a low trusted user

https://developers.google.com/recaptcha/docs/v3
