### ISSUE TITLE
Registration for referred friend

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#23]
Referral user repeated many times,while no mail send to it, and no registration has been done.
Time Stamp: 11/21/2019  12:53:00 PM
![image](https://user-images.githubusercontent.com/58039276/69347709-a95b4e00-0c7d-11ea-991e-ecb9c07324c7.png)

**Comment by enuat** [comment]
Already tracked under #21

**Comment by enuat** [comment]
Joining Date will be renamed to "Invited On"

It will show as many entires as you have clicked on "send  email" button. An entry is made everytime.

**Comment by Msebaie2** [comment]
please make sure that the button of send mail is clickable and receive a confirmation pop up contains that the mail has been send to avoid this issue.

**Comment by enuat** [comment]
Yes, that will be taken care as part of #21

**Comment by Msebaie2** [comment]
any updates

**Comment by enuat** [comment]
Please close this , as its tracked in #21 

and #21 has been fixed on Dev,  we will update you once its pushed to server
