### ISSUE TITLE
Get pending reward

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#24]
Got   30$ dollars as a referrer rewards instead of 25$
![image](https://user-images.githubusercontent.com/58039276/69347784-c859e000-0c7d-11ea-80b3-2df343447ff8.png)
Time Stamp: 11/21/2019  2:08:00 PM

**Comment by enuat** [comment]
Which user are you referring to?

**Comment by Msebaie2** [comment]
Mostafa ElSebaie (m.elsebaie@arabyads.com)
--

**Comment by enuat** [comment]
We've fixed the issue, admin changes were not clearing the cache.

Now we've fixed it, you can make changes to the bonus amount, create a new account and verify the same.

**Comment by Msebaie2** [comment]
Solved
