### ISSUE TITLE
Should get 25$ dollars reward

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#25]
Earning amount refelected as 22$ instead of 25$
Time Stamp: 11/21/2019  2:11:00 PM
![image](https://user-images.githubusercontent.com/58039276/69347875-ee7f8000-0c7d-11ea-88d3-c1de5f0e7363.png)

**Comment by enuat** [comment]
Its not $22 as bonus amount, it means you will earn 22% Of that users earnings 

We've added % to that figure.

**Comment by Msebaie2** [comment]
Closed
