### ISSUE TITLE
Website not compatible with Tablet Mode view 

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#26]
![image](https://user-images.githubusercontent.com/58039276/69533830-402b5180-0f81-11ea-97e0-ea44f69147a4.png)

Website not working if using Tablet or IPad

**Comment by Msebaie2** [comment]
any updates

**Comment by Msebaie2** [comment]
Still the same check the below screenshot,
and please if you don't face the same issue just try to make refresh to the page.

![image](https://user-images.githubusercontent.com/58039276/71321671-d6419180-24c5-11ea-99cb-7bb23ff0381c.png)

**Comment by enuat** [comment]
We've fixed this on our dev server.

Checking why not reflecting on server.

**Comment by Msebaie2** [comment]
awaiting your update

**Comment by Msebaie2** [comment]
any updates

**Comment by enuat** [comment]
Hi,

We've implemented the code to actually detecting the device and load the website.

To test it, you need to use actual device or simulator website.

We've tested this and looks fine in almost all resolution, minor improvements are being fixed and updated in later releases.

Please verify.
![image](https://user-images.githubusercontent.com/58430125/71407045-eee5af00-265f-11ea-820c-174b59acc51e.png)

**Comment by Msebaie2** [comment]
checked and closed
