### ISSUE TITLE
Shopping trips

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#27]
![image](https://user-images.githubusercontent.com/58039276/69950878-d66cf380-14fc-11ea-8764-6e35beffc634.png)

After making some transactions through Skyscanner, there are no data available in Shopping trips tab, as it's should have all trips history with details.

**Comment by enuat** [comment]
Trip data is filtered by month (selection at top right of the table) @ https://prnt.sc/q8plj0

Please change this to different month to see the trip data.

By default this shows the current month.

Please verify and mark as closed.

**Comment by Msebaie2** [comment]
You can check the below, however i'm asking about Dec data

![image](https://user-images.githubusercontent.com/58039276/70517903-0ee68000-1b42-11ea-84dc-c33c00651d47.png)

![image](https://user-images.githubusercontent.com/58039276/70517923-186fe800-1b42-11ea-8f38-f230172626ed.png)

**Comment by enuat** [comment]
Hi,

Please share this user login details.

Thanks.

**Comment by Msebaie2** [comment]
Moustafa.Elsebaie@gmail.com
Asd1236*
Note: You have to login to Google then use yajny by login via google link.

**Comment by enuat** [comment]
Google sent a notification to your phone. Tap Yes on the notification, then tap 43 on your phone to continue.

**Comment by Msebaie2** [comment]
done

**Comment by enuat** [comment]
Thanks

**Comment by enuat** [comment]
I believe this is closed. Please check.

Logut and login again to check this. Already replied on CRM

**Comment by Msebaie2** [comment]
Solved
closed
