### ISSUE TITLE
Account setting >> Mobile number

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#29]
![image](https://user-images.githubusercontent.com/58039276/69951930-df5ec480-14fe-11ea-8ef6-b750a8eaf7db.png)

Account setting >> Mobile number >> Update mobile number
If I need to verify my mobile number, OTB SMS not received.

**Comment by enuat** [comment]
We are able to receive SMS, reference ->  https://ibb.co/F4DRSzT

Please check unifonic dashboard  as to why your numbers are not receiving SMS

**Comment by Msebaie2** [comment]
Retest to check SMS, but not received.
request SMS on 11:40 AM 04 Dec 19.
Mobile number # +201009000492

**Comment by enuat** [comment]
Please login and see the SMS sent log @ https://software.unifonic.com/en/textmessages/reports
https://prnt.sc/q60ybh

For us, it works every-time. Just now tested again.

Moreover, we've enabled debug mode and checked the browser for response status @ https://prnt.sc/q63lad

You may contact Unifonic once for more clarity.

The SMS Integration is working fine.

**Comment by Msebaie2** [comment]
Solved.
