### ISSUE TITLE
Home- Earn & Refer- Send Email button is not linkable and no action happens.

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#3]
**Steps**

1. Click My Account
2. Click Refer & Earn
3. Enter valid email 
4. Click Send Email

**Actual Result:**
Send Email button is not linkable and no action happens.

**Expected Result**
Send email should be linkable.

**Comment by enuat** [comment]
Already being tracked @ https://github.com/MirnaHamdy/Yajny/issues/21
