### ISSUE TITLE
FB refer

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#30]
New account created through the below link as a FB post referrer, but not reflected on refer and earn tab for referrer account New account with FB accounts (Mostafa.Elsebaie@outlook.com)
Referrer account via FB post (Moustafa.Elsebaie@gmail.com)

https://yajnyweb.enactweb.com/en/?refCode=01VPO&fbclid=IwAR2LjY2mNJEZ5pgCXH7ZSIphdZplve-0MN4KGC0xWxlO4DXF3eujVjOg-ts

**Comment by enuat** [comment]
This is been fixed, we've registered a new social user with above-mentioned referral code.

**Comment by Msebaie2** [comment]
Solved
