### ISSUE TITLE
Home Page - Did someone refer you? || Iphone

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#31]
When Try to click on (Did someone refer you?) nothing happened and it should open new button to insert the referrer code.

**Comment by enuat** [comment]
Works just fine

https://drive.google.com/file/d/1hiKqWk8VZOQ6SFIYLvvap1A-PQZOzrzt/view

**Comment by Msebaie2** [comment]
Solved Closed
