### ISSUE TITLE
Iphone || Safari browser

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#33]
Yajny website not compatible with Safari web browser on Iphone

**Comment by Msebaie2** [comment]
![image](https://user-images.githubusercontent.com/58039276/70389048-ee43ec00-19c2-11ea-86e3-61f8331ad261.png)

check this screenshot as safari not working

**Comment by MirnaHamdy** [comment]
@enuat any updates ?

**Comment by enuat** [comment]
We have tested it on iPhone and Safari on Mac , it looks just fine.

Your screenshot appears to be Safari on Windows which is highly unstable and hardly used.

References

https://ibb.co/FswSvQr
https://ibb.co/Wc20DM9 

https://ibb.co/nr82DTS
https://ibb.co/TtbHfBX
https://ibb.co/6n2QXcQ
https://ibb.co/hBxLxHF

**Comment by Msebaie2** [comment]
Check and closed
