### ISSUE TITLE
Stores are not clickable

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#35]
When make a search on any store like Noon for ex. the top stores on left side are not clickable.

![image](https://user-images.githubusercontent.com/58039276/70542360-4587bf00-1b71-11ea-99ba-978174492254.png)

**Comment by enuat** [comment]
Fixed.

Can be verified here
https://yajnyweb.enactweb.com/en/search?search_item=noo&sbtn=

**Comment by Msebaie2** [comment]
Solved and closed
