### ISSUE TITLE
Cash Back percentage

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#36]
I set cash back with 120% but not reflected on the store.

View from Admin page
![image](https://user-images.githubusercontent.com/58039276/70607777-bf6a8780-1c07-11ea-95e4-12b17eba3b21.png)

User View
![image](https://user-images.githubusercontent.com/58039276/70607816-cee9d080-1c07-11ea-9971-2dd6b010c2a3.png)

**Comment by enuat** [comment]
Isn't this closed via CRM?

**Comment by Msebaie2** [comment]
updated and closed
