### ISSUE TITLE
Sale transaction delete

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#37]
When try to delete sale transaction face the below error

![image](https://user-images.githubusercontent.com/58039276/70701572-42a5df00-1cd5-11ea-8597-3fbee4b39707.png)

**Comment by enuat** [comment]
A sale record can't be deleted until it's removed from all reference tables.

Practically, there's no use case where you need to delete a sale transaction, at max, you may want to change the information.

**Comment by MirnaHamdy** [comment]
Ok, So please just display a message says that, not show an exception.

**Comment by enuat** [comment]
Now, it shows error like 

![image](https://user-images.githubusercontent.com/58430125/71337216-9edbef00-2570-11ea-9dd3-04539c6ea907.png)

**Comment by Msebaie2** [comment]
Solved and closed
