### ISSUE TITLE
Total amount

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#38]
Total amount not matched with header 
this account have 94.05 $, but the reflected on header is 84.05$ 
Account (Moustafa.Elsebaie@gmail.com)
![image](https://user-images.githubusercontent.com/58039276/70720864-4c433d00-1cfd-11ea-93ba-c419b3f21ca7.png)

**Comment by enuat** [comment]
In header, the amount shown is Available for payment + pending (for both, cashback & reward) => This approach is benchmarked  from cashback industry leading portals.

Total Cashback Earned is already highlighted in My Account page.

So, both amount will not match.

Hope this clarifies.

**Comment by Msebaie2** [comment]
Thanks, Solved.
