### ISSUE TITLE
IOS mobile

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#39]
Check the below screenshot, and it's recommend android while it's supposed to recommend IOS app.

![IMG_0001](https://user-images.githubusercontent.com/58039276/71322201-b0b88600-24cd-11ea-83d9-723853261f19.PNG)

**Comment by enuat** [comment]
This will be made dynamic with URL when iOS app is deployed..

For now, we've hidden the call-to-action and noted in our TO DO..

**Comment by Msebaie2** [comment]
the url is hidden closed till IOS app deploying

**Comment by Msebaie2** [comment]
closed
