### ISSUE TITLE
My Account- Refer & Earn- Home link is not linkable and doesn't redirect to the homepage

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#4]
1. Login through Gmail.
2. Click on My Account. 
3. Click on Refer & Earn.
4. Below the header, click on the Home link.

**Actual Result**

Home link is not linkable and doesn't redirect to the homepage
https://drive.google.com/file/d/1c4Ew0MXICRFPN4-Pbj_y8l___H0z0kel/view?usp=sharing

**Expected Result:**
The home link should be linkable and redirect to the homepage.

**Comment by enuat** [comment]
Fixed

**Comment by Msebaie2** [comment]
Working and closed
