### ISSUE TITLE
drop down menu

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#40]
Kindly check the below screenshot as the drop down menu not compatible

![image](https://user-images.githubusercontent.com/58039276/71322345-515b7580-24cf-11ea-84fa-7df60c1b2661.png)
e

**Comment by enuat** [comment]
This is staging version for your configuration.

Please refer the documentation and configure the menu and it will look all perfect as it was.

Document @ 
![image](https://user-images.githubusercontent.com/58430125/71337126-312fc300-2570-11ea-8e5e-c6bbb7ee757e.png)

**Comment by Msebaie2** [comment]
please check the below screenshot as after clear the cash and the issue still exist

![image](https://user-images.githubusercontent.com/58039276/71348889-38f26600-2576-11ea-9667-adda4d89bb62.png)

**Comment by enuat** [comment]
Hey,

It's not just about cache, you had to configure data also.

For your understanding, I have configured same data multiple time and here is the look;

![image](https://user-images.githubusercontent.com/58430125/71349168-4f0f1f00-2594-11ea-8051-8ee903183e04.png)

**Comment by Msebaie2** [comment]
Closed
