### ISSUE TITLE
navigate all store by alphabet 

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#41]
check the below screenshot as on right side of screen you will find alphabet sorting with wrong view.

IOS Mobile.

![Image-1](https://user-images.githubusercontent.com/58039276/71322567-94b6e380-24d1-11ea-8d5c-8385a667bc8d.jpg)

**Comment by enuat** [comment]
This is part of the design.
It's part of the benchmark @ 
![image](https://user-images.githubusercontent.com/58430125/71337064-e4e48300-256f-11ea-873d-d7274ee98f37.png)

**Comment by Msebaie2** [comment]
pending tell we add stores and retest

**Comment by Msebaie2** [comment]
but tell we add the stores we need to change the below in Arabic page to be with Arabic Alphabet and in mobile view we need to remove (O- and 9) and replace them with # like rakuten

**Comment by Msebaie2** [comment]
![image](https://user-images.githubusercontent.com/58039276/71352144-2b40de80-257e-11ea-8c6f-92cd29cda9fc.png)

this screen from laptop view

**Comment by Msebaie2** [comment]
case closed, we will update it when we receive source code.
