### ISSUE TITLE
Contact request

### ISSUE THREAD

**Issue by Msebaie2** [MirnaHamdy/Yajny#43]
If I try to send SMS with less than 6 characters face the below error, while it should be a pop up notification with the error.

![image](https://user-images.githubusercontent.com/58039276/71353751-b2905100-2582-11ea-996b-cd1a7539a5b0.png)

**Comment by enuat** [comment]
Issue fixed

![image](https://user-images.githubusercontent.com/58430125/71396359-bd5ceb80-263f-11ea-9f3e-e146fa39aac4.png)

**Comment by Msebaie2** [comment]
you removed the characters length, issue closed.
