### ISSUE TITLE
Validation message is not cleared and need to be more descriptive.

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#5]
**Steps:**

1. Login
2. Click on **My Account**
3. Click on **Earn & Refer**
4. Leave the field **empty/Enter Invalid data** 
5. Click **Send Email**

**Actual Result:**

Validation message is **Not Validate** which is not cleared.
https://drive.google.com/file/d/1Jc3gwx-7ScKjC7hiJVAEqFo48et9uy8b/view?usp=sharing

**Expected Result**
The validation message expected to have appeared when the field is empty is 
**Email Field can't be empty** 
or 
**Please enter your email**

**Comment by Msebaie2** [comment]
any updates

**Comment by Msebaie2** [comment]
Solved
