### ISSUE TITLE
Favicon is not clickable and nothing is added to your favourite list.

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#6]
**Steps:**
1. Login 
2. Click on All Stores drop-down menu
3. Click on  See All Stores.0
4. Open Any store
5. Click on Add Favicon of any product.

**Actual Result:**
Favicon is not clickable and nothing is added to your favourite list.
https://drive.google.com/file/d/1UAz_JRJiAvtwvQ1FPg-QPBf1NalZVwYg/view?usp=sharing

**Expected Result:**
The favicon should be clickable and the product should be added to your Favorite list.

**Comment by enuat** [comment]
Unable to reproduce this. Its working fine , we checked with multiple logins.

**Comment by Msebaie2** [comment]
Working and closed
