### ISSUE TITLE
After creating a new account the verification email is not sent to your email to activate your account.

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#7]
1. Click sign up 
2. enter valid email
3. Enter your password
4. click on Join Now

Actual Result:
After creating a new account the verification email is not sent to your email to activate your account.

Expected Result:
After creating a new account the verification email should sent to your email.

**Comment by enuat** [comment]
I believe this is Closed. 
You need to check mailtrap login for all emails.

**Comment by Msebaie2** [comment]
Issue Closed
