### ISSUE TITLE
Login buttons are not clickable (FB/G/Sign in through the website)

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#8]
1. Navigate to the homepage.
2. Click on SIGN IN link.
3. Click on Continue With Facebook/Continue With Google/SignIn 

**Actual Result:**
No actions happen and the buttons are not clickable.

**Expected Result:**
The buttons should be clickable and I can sign in through FB & G & Login through the website.

**Comment by enuat** [comment]
Unable to reproduce this issue.

**Comment by enuat** [comment]
Fixed

**Comment by Msebaie2** [comment]
Working and closed
