### ISSUE TITLE
Login/Join Now- Once you clicked on fields to start typing something placeholders don't disappear.

### ISSUE THREAD

**Issue by MirnaHamdy** [MirnaHamdy/Yajny#9]
**For More Usability:**

**Steps:**
1. Navigate to the homepage
2. Click on Member Sign in
3. Click on Email field/click on the password field 
Also 
4. Click on Join Now Tab
5. Click on the Email field/click on the password field 

**Actual Result:**

Once you clicked on fields to start typing something placeholders don't disappear.

**Expected Result:**

Once you clicked on fields to start typing something placeholders should be disappeared

**Comment by enuat** [comment]
Can you pls share the screenshot, unable to reproduce

**Comment by Msebaie2** [comment]
closed
